server:
  port:
    9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
